name: build

on: pull_request

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Generate
      run: |
        go install golang.org/dl/go1.16@latest
        go1.16 download
        go generate -v ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
